title: "Roadmap Proposal"
labels: ["Feature Requests"]
body:
  - type: markdown
    attributes:
      value: |
        ## Proposal Template
        Please provide the following details for your proposal.
  - type: textarea
    id: proposal-description
    attributes:
      label: Write your proposal here. 
      description: A clear and concise description of your proposal. Leave your email if you prefer communication over email.
    validations:
      required: true

