title: "[Feature Request] "
labels: ["Feature Requests"]
body:
  - type: markdown
    attributes:
      value: |
        ## Proposal Template
        Please provide the following details for your proposal.
  - type: input
    id: proposal-title
    attributes:
      label: Proposal Title
      description: A short and descriptive title for your proposal.
    validations:
      required: true
  - type: textarea
    id: proposal-description
    attributes:
      label: Write your proposal here. 
      description: A clear and concise description of your proposal. Leave your email if you prefer communication over email.
    validations:
      required: true

